argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - argocd.zhaho.duckdns.org
      paths:
        - /
      # tls:
      #   - secretName: argocd-tls
      #     hosts:
      #       - argocd.zhaho.duckdns.org